legislator/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from legislator import views

ad = 9
urlpatterns = [
    url(r'^(?P<index>conflict|not_voting)/(?P<ad>[1-9])/$', views.index, name='index'),
    url(r'^(?P<index>conflict|not_voting)/$', views.index, {'ad': ad}, name='index'),
    url(r'^counties/(?P<ad>\d+)/$', views.counties, name='counties'),
    url(r'^counties/$', views.counties, {'ad': ad}, name='counties'),
    url(r'^county/(?P<county>.+)/(?P<ad>\d+)/$', views.county, name='county'),
    url(r'^county/(?P<county>.+)/$', views.county, {'ad': ad}, name='county'),
    url(r'^committee/(?P<committee>.+)/(?P<ad>\d+)/$', views.committee, name='committee'),
    url(r'^committee/(?P<committee>.+)/$', views.committee, {'ad': ad}, name='committee'),
    url(r'^info/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.info, name='info'),
    url(r'^voter_sp/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.voter_standpoints, name='voter_standpoints'),
    url(r'^voter/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.voter_detail, name='voter_detail'),
    url(r'^biller/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.biller_detail, name='biller_detail'),
    url(r'^pc/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.personal_political_contributions, name='personal_political_contributions'),
    url(r'^platformer/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.platformer_detail, name='platformer_detail'),
    url(r'^report/(?P<index>biller|conscience_vote|vote|ly)/(?P<ad>\d+)/$', views.chart_report, name='chart_report'),
    url(r'^report/(?P<index>biller|conscience_vote|vote|ly)/$', views.chart_report, {'ad': ''}, name='chart_report'),
    url(r'^report/political_contributions/(?P<index>\S+)/(?P<compare>\S+)/(?P<party>\S+)/$', views.political_contributions_report, name='political_contributions_report'),
]

ly/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.conf import settings
from rest_framework import routers

from . import views as ly_views
from api import views as api_views

#--> rest framework url
router = routers.DefaultRouter()
router.register(r'legislator', api_views.LegislatorViewSet)
router.register(r'legislator_terms', api_views.LegislatorDetailViewSet)
router.register(r'committees', api_views.CommitteesViewSet)
router.register(r'legislator_committees', api_views.Legislator_CommitteesViewSet)
router.register(r'sittings', api_views.SittingsViewSet)
router.register(r'vote', api_views.VoteViewSet)
router.register(r'legislator_vote', api_views.Legislator_VoteViewSet)
router.register(r'bill', api_views.BillViewSet)
router.register(r'law', api_views.LawViewSet)
router.register(r'legislator_bill', api_views.Legislator_BillViewSet)
router.register(r'attendance', api_views.AttendanceViewSet)
router.register(r'candidates', api_views.CandidatesViewSet)
router.register(r'candidates_terms', api_views.Candidates_TermsViewSet)
router.register(r'standpoint', api_views.StandpointViewSet)
#<--
urlpatterns = [
    url(r'^$', ly_views.home, name='home'),
    url(r'^legislator/', include('legislator.urls', namespace="legislator")),
    url(r'^candidates/', include('candidates.urls', namespace="candidates")),
    url(r'^vote/', include('vote.urls', namespace="vote")),
    url(r'^bill/', include('bill.urls', namespace="bill")),
    url(r'^about/$', ly_views.about, name='about'),
    url(r'^reference/$', ly_views.reference, name='reference'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^accounts/logout/$', ly_views.logout, name='logout'),
    url(r'^api/', include(router.urls)),
]

vote/urls.py
from django.conf.urls import url
from vote import views

urlpatterns = [
    url(r'^$', views.votes, name='votes'),
    url(r'^(?P<vote_id>\S+)/$', views.vote, name='vote_detail'),
]

vote/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.postgres.fields import JSONField


class Vote(models.Model):
    voter = models.ManyToManyField('legislator.LegislatorDetail', through='Legislator_Vote')
    uid = models.CharField(max_length=32, primary_key=True)
    sitting = models.ForeignKey('sittings.Sittings', related_name='votes')
    vote_seq = models.CharField(max_length=10)
    category = models.CharField(max_length=100, blank=True, null=True)
    content = models.TextField()
    conflict = models.NullBooleanField()
    result = models.CharField(blank=True, null=True, max_length=50)
    results = JSONField(null=True)
    def __unicode__(self):
        return self.uid

class Legislator_Vote(models.Model):
    legislator = models.ForeignKey('legislator.LegislatorDetail', related_name='votes')
    vote = models.ForeignKey(Vote)
    decision = models.IntegerField(db_index=True, blank=True, null=True)
    conflict = models.NullBooleanField(db_index=True)

    class Meta:
        unique_together = ("legislator", "vote")

vote/views.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q, F, Sum
from django.db import connections
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import IntegrityError, transaction

from haystack.query import SearchQuerySet

from .models import Vote, Legislator_Vote
from search.models import Keyword
from standpoint.models import Standpoint, User_Standpoint
from search.views import keyword_list, keyword_been_searched, keyword_normalize
from .tasks import update_vote_index
from commontag.views import paginate


def votes(request):
    qs = Q(content=request.GET['keyword']) if request.GET.get('keyword') else Q()
    qs = qs & Q(conflict=True) if request.GET.get('conscience') else qs
    qs = qs & Q(tags_num__gt=0) if request.GET.get('has_tag') else qs
    qs = qs & Q(tags__in=[request.GET['tag']]) if request.GET.get('tag') else qs
    votes = SearchQuerySet().filter(qs).models(Vote).order_by('-date', 'vote_seq')
    votes = paginate(request, votes)
    keywords = [x.content for x in SearchQuerySet().filter(category__exact=2).models(Keyword).order_by('-hits')]
    standpoints = Standpoint.objects.values('title').annotate(pro_sum=Sum('pro')).order_by('-pro_sum').distinct()
    get_params = '&'.join(['%s=%s' % (x, request.GET[x]) for x in ['keyword', 'conscience', 'has_tag'] if request.GET.get(x)])
    return render(request, 'vote/votes.html', {'votes': votes, 'conscience': request.GET.get('conscience'), 'keyword': request.GET.get('keyword', ''), 'keyword_obj': keywords, 'hot_keyword': keywords[:5], 'hot_standpoints': standpoints[:5], 'get_params': get_params})

def vote(request, vote_id):

    vote = get_object_or_404(Vote.objects.select_related('sitting'), uid=vote_id)
    if request.user.is_authenticated():
        if request.POST:
            with transaction.atomic():
                if request.POST.get('keyword', '').strip():
                    standpoint_id = u'vote-%s-%s' % (vote_id, request.POST['keyword'].strip())
                    Standpoint.objects.get_or_create(uid=standpoint_id, title=request.POST['keyword'].strip(), vote_id=vote_id, user=request.user)
                    update_vote_index.delay(vote_id)
                elif request.POST.get('pro'):
                    User_Standpoint.objects.create(standpoint_id=request.POST['pro'], user=request.user)
                    Standpoint.objects.filter(id=request.POST['pro']).update(pro=F('pro') + 1)
                    update_vote_index.delay(vote_id)
                elif request.POST.get('against'):
                    User_Standpoint.objects.get(standpoint_id=request.POST['against'], user=request.user).delete()
                    Standpoint.objects.filter(id=request.POST['against']).update(pro=F('pro') - 1)
                    update_vote_index.delay(vote_id)

    standpoints_of_vote = Standpoint.objects.filter(vote_id=vote_id)\
                                            .order_by('-pro')
    if request.user.is_authenticated():
        standpoints_of_vote = standpoints_of_vote.extra(select={
            'have_voted': "SELECT true FROM standpoint_user_standpoint su WHERE su.standpoint_id = standpoint_standpoint.id AND su.user_id = %s" % request.user.id,
        },)
    standpoints = list(Standpoint.objects.filter(vote__isnull=False, pro__gt=0).values_list('title', flat=True).distinct())
    return render(request, 'vote/vote.html', {'vote': vote, 'keyword_obj': standpoints, 'standpoints_of_vote': standpoints_of_vote})

vote/templates/vote/vote.html
{% extends "base.html" %}
{% load ly_extras %}
{% load staticfiles %}

{% block title %}
    {% if vote %}
        <title>立委投票指南:{{ vote.sitting.name }}({{ vote.sitting.date|date:"Y-m-d" }})第{{vote.vote_seq}}個表決</title>
        <meta property="og:title" content="立委投票指南:{{ vote.sitting.name }}({{ vote.sitting.date|date:"Y-m-d" }})第{{vote.vote_seq}}個表決"/>
        <meta itemprop="name" content="立委投票指南:{{ vote.sitting.name }}({{ vote.sitting.date|date:"Y-m-d" }})第{{vote.vote_seq}}個表決">
    {% else %}
        <title>立委投票指南:單一表決名單</title>
        <meta property="og:title" content="立委投票指南:單一表決名單"/>
        <meta itemprop="name" content="立委投票指南:單一表決名單">
    {% endif %}
{% endblock title %}

{% block right %}
    {% if vote %}
    {% if vote.category == '變更議程順序' %}
    <div class="alert lead">
        <button type="button" class="close">&times;</button>
        <p><strong>注意！！</strong> 此表決可能為變更議程順序的表決，還在決定審議順序階段，並非各個單一提案的通過與否。</p>
        <p>各個單一提案也請特別注意順序號碼，由小到大表示由先到後。</p>
    </div>
    {% endif %}
    <div class="row-fluid">
        <div class="span3">
            <div class="row-fluid">
            {% for fragment in vote.results %}
                <div class="span12">
                    <h3>
                        {% if fragment.decision == "反對" %}
                            <i class="fa fa-times-circle text-error">
                        {% elif fragment.decision == "贊成" %}
                            <i class="fa fa-check-circle text-success">
                        {% elif fragment.decision == "沒投票" %}
                            <i class="fa fa-bed muted">
                        {% else %}
                            <i class="fa fa-question-circle text-warning">
                        {% endif %}
                        {{ fragment.decision }} </i>
                    </h3>
                    <ul>
                    {% for element in fragment.party_list %}
                        <li data-toggle="collapse" data-target="#ref_vote_{{fragment.decision}}_{{element.party}}"><span>{{element.party}}：{{element.legislators|length}}人 <i class="fa fa-caret-square-o-down"></i></span></li>
                        <div id="ref_vote_{{fragment.decision}}_{{element.party}}" class="collapse">
                            <ul class="inline">
                            {% for ly in element.legislators %}
                                <li><a href="{% url 'legislator:voter_standpoints' legislator_id=ly.legislator_id ad=vote.sitting.ad %}" rel="tooltip" title="這位立委的表決紀錄">{{ly.name}}</a></li>
                            {% endfor %}
                            </ul>
                        </div>
                    {% endfor %}
                    </ul>
                </div><!--end: span -->
            {% endfor %}
            </div><!--end: row-fluid -->
            {% endif %}
        </div><!--end: span -->

        <div class="span5">
            <div class="hero-unit">
                <span class="badge badge-important pull-right"><font class="lead">{{vote.result|vote_result:'cht'}}</font></span>
                <a href="{{vote.sitting.links.pdf}}" target="_blank"><i class="fa fa-file-pdf-o"> 立院會議記錄(pdf)</i></a>
                <p class="text-success">表決日期：{{ vote.sitting.date|date:"Y-m-d" }}</p>
                <p>{{ vote.content|linebreaksbr }}</p>
            </div>
        </div><!--end: span -->

        <div class="span4" style="background-color: #ffff001a">
            <form action="" method="post" class="form-inline">
                {% csrf_token %}
                <br>
                <fieldset>
                    <label>請輸入最能代表這個提案的標籤：</label>
                    {% if user.is_authenticated %}
                        <input type="search" name="keyword" id="keyword" maxlength="20" placeholder="建議:動+名詞，如降屯房稅">
                        <button type="submit" class="btn">確定</button>
                    {% else %}
                        <a href="/login/facebook/?next={% url 'vote:vote_detail' vote.uid %}"><i class="fa fa-sign-in"> 登入加標籤</i></a>
                    {% endif %}
                </fieldset>
                {% with size=3 %}
                {% for standpoint in standpoints_of_vote %}
                    {% if forloop.counter0 == size %}
                        <button type="button" class="btn " data-toggle="collapse" data-target="#ref_more"><font>..... 其他標籤 <i class="fa fa-angle-down"></i></font></button>
                        <div id="ref_more" class="collapse">
                    {% endif %}
                    <h4>{{standpoint.pro}}人認為是
                        <span class="label label-success">{{standpoint}}</span>
                        {% if user.is_authenticated %}
                            {% if standpoint.have_voted %}
                                <button name="against" class="btn" value="{{standpoint.id}}">取消 +1</button>
                            {% else %}
                                <button name="pro" class="btn" value="{{standpoint.id}}">+1</button>
                            {% endif %}
                        {% else %}
                        <a href="/login/facebook/?next={% url 'vote:vote_detail' vote.uid %}" class="btn btn-default"><i class="fa fa-sign-in"> 登入投票</i></a>
                        {% endif %}
                    </h4>
                {% endfor %}
                {% if standpoints_of_bill|length > size %}
                    </div>
                {% endif %}
                {% endwith %}
            </form>
        </div>
    </div><!--end: row-fluid -->
    <hr>
    <div id="disqus_thread"></div>
{% endblock right %}

{% block script %}
    {% include "common/keyword_auto_complete.html" %}
    <script>
        $(document).ready( function() {
            $('#vote').addClass('active');
            $("#other_tags.collapse").collapse();
            $("[rel='tooltip']").tooltip();
        });
    </script>
{% endblock script %}

vote/templates/vote/vote_d3_pie_chart.html
{% load ly_extras %}
<style>

    .arc text {
        font: 18px sans-serif;
        font-weight: bold;
    }

    .arc path {
        stroke: #fff;
    }

</style>
<script src="https://s3-ap-northeast-1.amazonaws.com/twly.tw/d3.min.js"></script>
<script>

    var data = {{data|as_json}}

    var width = 400,
    height = 270,
    radius = Math.min(width, height) / 2 -20,
    labelr = radius + 10; // radius for label anchor

    var color = d3.scale.ordinal()
    .range(["#FF66CC", "#999999", "#66CC66", "#FFCC33"])
    .domain(['disagree', 'abstain', 'agree', 'not_voting']);

    var legend = d3.scale.ordinal()
    .range(["反對", "棄權", "贊成", "沒投票"])
    .domain(['disagree', 'abstain', 'agree', 'not_voting']);

    var arc = d3.svg.arc()
    .outerRadius(radius - 10)
    .innerRadius(0);

    var pie = d3.layout.pie()
    .sort(null)
    .value(function(d) { return d.value; });

    var svg = d3.select("#d3").append("svg")
    .attr("width", width)
    .attr("height", height)
    .append("g")
    .attr("transform", "translate(" + width / 2 + "," + height / 2 + ")");

    var g = svg.selectAll(".arc")
    .data(pie(d3.entries(data)))
    .enter().append("g")
    .attr("class", "arc");

    g.append("path")
    .attr("d", arc)
    .style("fill", function(d) { return color(d.data.key); });

    g.append("text")
    .attr("transform", function(d) {
        var c = arc.centroid(d),
        x = c[0],
        y = c[1],
        // pythagorean theorem for hypotenuse
        h = Math.sqrt(x*x + y*y);
        return "translate(" + (x/h * labelr) +  ',' +
        (y/h * labelr) +  ")";
    })
    .attr("dy", ".35em")
    .attr("text-anchor", function(d) {
        return (d.endAngle + d.startAngle)/2 > Math.PI ?
        "end" : "start";
    })
    .text(function(d) {
        if (d.value != 0)
        return legend(d.data.key) + '：' + d.value;
    })
    .style("fill", function(d) { return color(d.data.key); });

</script>

vote/templates/vote/vote_summary.html
{% load ly_extras %}
{% load highlight %}

<li class="media">
    <div class="media-body well">
        <div class="muted media-heading">
            第{{ fragment.ad }}屆（{{ fragment.date|date:"Y-m-d" }}）第{{ fragment.vote_seq }}個表決
        </div>
        <h5 class="text-success">表決內容</h5>
        {% if keyword %}
            <p>
                <small class="muted">（前文略）</small>
                {% highlight fragment.text with keyword %}
                <small class="muted">（後文略）</small>
            </p>
        {% else %}
            <p>{{ fragment.text|linebreaksbr }}</p>
        {% endif %}
        <blockquote>
            <a href="{% url 'vote:vote_detail' fragment.uid %}" rel="tooltip" title="查看各立委投什麼票"><i class="fa fa-pie-chart"> 看誰贊成誰反對</i></a>
            <a class="pull-right" href="{% url 'vote:vote_detail' fragment.uid %}" ><i class="fa fa-tag"> 我要加標籤、投票</i></a>
        </blockquote>
        {% if fragment.tags %}
            <h5 class="text-success">標籤</h5>
            {% for title, votes in fragment.tags %}
                <a href="{% url 'vote:votes' %}?tag={{title}}" rel="tooltip" title="有同樣標籤的表決">
                    <font style="color: {% cycle '#FF0099' '#FF33CC' '#FF6699' '#FF9966' '#FFCC00' %};">{{title}}</font>
                </a>
                （{{votes}}票）&nbsp;&nbsp;
            {% endfor %}
        {% endif %}
        <h5 class="text-success">表決結果</h5>
            <span class="label label-inverse"><font class="lead">{{fragment.result|vote_result:'cht'}}</font></span>
            {% if fragment.conflict %}
                <small class="text-error"><font class="lead text-error">有立委脫黨投票</font></small>
            {% endif %}
    </div>
</li>

vote/templates/vote/votes.html
{% extends "base.html" %}
{% load ly_extras %}
{% load highlight %}

{% block title %}
    {% if conscience %}
        <title>立委投票指南:脫黨表決檢索</title>
        <meta property="og:title" content="立委投票指南:脫黨表決檢索"/>
        <meta itemprop="name" content="立委投票指南:脫黨表決檢索">
    {% else %}
        <title>立委投票指南:全表決檢索</title>
        <meta property="og:title" content="立委投票指南:全表決檢索"/>
        <meta itemprop="name" content="立委投票指南:全表決檢索">
    {% endif %}
{% endblock %}

{% block right %}
    <div class="span2">
    </div>
    <div class="span8 hero-unit" style="padding-bottom: 30px;">
        {% include "common/search_keyword_form.html" with placeholder_text="例:核四 食品安全" advance_search="common/vote_conscience_checkbox.html" %}
        <p>
        {% if hot_standpoints %}
            熱門標籤：
            {% for standpoint in hot_standpoints %}
            <a href="{% url 'vote:votes' %}?tag={{standpoint.title}}" rel="tooltip" title="包含此標籤的表決"><font style="color: #9F0050;"><b>{{standpoint.title}}</b>&nbsp;</font></a>
            {% endfor %}
        {% endif %}
        {% if hot_keyword %}
            <br>熱門搜尋：
            {% for keyword in hot_keyword %}
            <a href="{% url 'vote:votes' %}?keyword={{keyword}}" rel="tooltip" title="包含此關鍵字的表決"><font style="color: #9F0050;"><b>{{keyword}}</b>&nbsp;</font></a>
            {% endfor %}
        {% endif %}
        </p>
        {% if votes %}
        <div class="well well-small">
            {{ votes.paginator.count }}個搜尋結果，這是第{{ votes.number }}頁（共{{ votes.paginator.num_pages }}頁）
        </div>
        <ul class="media-list">
            {% for fragment in votes %}
                {% include "vote/vote_summary.html" %}
            {% endfor %}
        </ul>
        {% include "common/pagination.html" with items=votes %}
        {% endif %}
    </div>
    <div class="span2">
    </div>
{% endblock right %}

{% block backtotop %}
    {{ block.super }}
{% endblock backtotop %}

{% block script %}
    {% include "common/keyword_auto_complete.html" %}
    <script>
        $(document).ready( function() {
            $('#vote').addClass('active');
            $("[rel='tooltip']").tooltip();
            $("#advanced_search.collapse").collapse();
        });
    </script>
{% endblock script %}