candidates/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from candidates import views

urlpatterns = [
    url(r'^$', views.counties, {"ad": 9}),
    url(r'^(?P<ad>\d+)/(?P<county>\S+)/(?P<constituency>\d+)/$', views.district, name='district'),
    url(r'^(?P<ad>\d+)/(?P<county>\S+)/$', views.districts, name='districts'),
    url(r'^(?P<ad>\d+)/$', views.counties, name='counties'),
    url(r'^pc/(?P<candidate_id>\S+)/(?P<ad>\d+)/$', views.pc, name='pc'),
]

legislator/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from legislator import views

ad = 9
urlpatterns = [
    url(r'^(?P<index>conflict|not_voting)/(?P<ad>[1-9])/$', views.index, name='index'),
    url(r'^(?P<index>conflict|not_voting)/$', views.index, {'ad': ad}, name='index'),
    url(r'^counties/(?P<ad>\d+)/$', views.counties, name='counties'),
    url(r'^counties/$', views.counties, {'ad': ad}, name='counties'),
    url(r'^county/(?P<county>.+)/(?P<ad>\d+)/$', views.county, name='county'),
    url(r'^county/(?P<county>.+)/$', views.county, {'ad': ad}, name='county'),
    url(r'^committee/(?P<committee>.+)/(?P<ad>\d+)/$', views.committee, name='committee'),
    url(r'^committee/(?P<committee>.+)/$', views.committee, {'ad': ad}, name='committee'),
    url(r'^info/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.info, name='info'),
    url(r'^voter_sp/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.voter_standpoints, name='voter_standpoints'),
    url(r'^voter/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.voter_detail, name='voter_detail'),
    url(r'^biller/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.biller_detail, name='biller_detail'),
    url(r'^pc/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.personal_political_contributions, name='personal_political_contributions'),
    url(r'^platformer/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.platformer_detail, name='platformer_detail'),
    url(r'^report/(?P<index>biller|conscience_vote|vote|ly)/(?P<ad>\d+)/$', views.chart_report, name='chart_report'),
    url(r'^report/(?P<index>biller|conscience_vote|vote|ly)/$', views.chart_report, {'ad': ''}, name='chart_report'),
    url(r'^report/political_contributions/(?P<index>\S+)/(?P<compare>\S+)/(?P<party>\S+)/$', views.political_contributions_report, name='political_contributions_report'),
]

ly/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.conf import settings
from rest_framework import routers

from . import views as ly_views
from api import views as api_views

#--> rest framework url
router = routers.DefaultRouter()
router.register(r'legislator', api_views.LegislatorViewSet)
router.register(r'legislator_terms', api_views.LegislatorDetailViewSet)
router.register(r'committees', api_views.CommitteesViewSet)
router.register(r'legislator_committees', api_views.Legislator_CommitteesViewSet)
router.register(r'sittings', api_views.SittingsViewSet)
router.register(r'vote', api_views.VoteViewSet)
router.register(r'legislator_vote', api_views.Legislator_VoteViewSet)
router.register(r'bill', api_views.BillViewSet)
router.register(r'law', api_views.LawViewSet)
router.register(r'legislator_bill', api_views.Legislator_BillViewSet)
router.register(r'attendance', api_views.AttendanceViewSet)
router.register(r'candidates', api_views.CandidatesViewSet)
router.register(r'candidates_terms', api_views.Candidates_TermsViewSet)
router.register(r'standpoint', api_views.StandpointViewSet)
#<--
urlpatterns = [
    url(r'^$', ly_views.home, name='home'),
    url(r'^legislator/', include('legislator.urls', namespace="legislator")),
    url(r'^candidates/', include('candidates.urls', namespace="candidates")),
    url(r'^vote/', include('vote.urls', namespace="vote")),
    url(r'^bill/', include('bill.urls', namespace="bill")),
    url(r'^about/$', ly_views.about, name='about'),
    url(r'^reference/$', ly_views.reference, name='reference'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^accounts/logout/$', ly_views.logout, name='logout'),
    url(r'^api/', include(router.urls)),
]

candidates/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.postgres.fields import ArrayField, JSONField


class Candidates(models.Model):
    uid = models.CharField(max_length=64, primary_key=True)
    name = models.CharField(max_length=100)
    former_names = ArrayField(
        models.CharField(max_length=100),
        null=True,
        default=None,
    )
    birth = models.DateField(blank=True, null=True)
    identifiers = JSONField(null=True)
    data = JSONField(null=True)

    def __unicode__(self):
        return self.name

class Terms(models.Model):
    id = models.CharField(max_length=70, primary_key=True)
    candidate = models.ForeignKey(Candidates)
    latest_term = models.ForeignKey('legislator.LegislatorDetail', blank=True, null=True)
    legislator = models.OneToOneField('legislator.LegislatorDetail', blank=True, null=True, related_name='elected_candidate')
    ad = models.IntegerField(db_index=True, )
    number = models.IntegerField(db_index=True, blank=True, null=True)
    priority = models.IntegerField(db_index=True, blank=True, null=True)
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=100, blank=True, null=True)
    party = models.CharField(db_index=True, max_length=100, blank=True, null=True)
    constituency = models.IntegerField(db_index=True)
    county = models.CharField(db_index=True, max_length=100)
    district = models.CharField(db_index=True, max_length=100, blank=True, null=True)
    votes = models.IntegerField(blank=True, null=True)
    votes_percentage = models.CharField(max_length=100, blank=True, null=True)
    elected = models.NullBooleanField(db_index=True)
    contact_details = JSONField(null=True)
    education = models.TextField(blank=True, null=True)
    experience = models.TextField(blank=True, null=True)
    remark = models.TextField(blank=True, null=True)
    image = models.URLField(blank=True, null=True)
    links = JSONField(null=True)
    platform = models.TextField(blank=True, null=True)
    politicalcontributions = JSONField(null=True)
    councilor = JSONField(null=True)
    cec_data = JSONField(null=True)

    class Meta:
        index_together = ['ad', 'county', 'constituency']

    def __unicode__(self):
        return self.name

candidates/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.db.models import Count, Q
from django.db import connections
from django.utils import timezone

from .models import Candidates, Terms
from legislator.models import LegislatorDetail
from elections.models import Elections


def counties(request, ad):
    regions = [
        {"region": "北部", "counties": ["臺北市", "新北市", "桃園市", "基隆市", "宜蘭縣", "新竹縣", "新竹市"]},
        {"region": "中部", "counties": ["苗栗縣", "臺中市", "彰化縣", "雲林縣", "南投縣"]},
        {"region": "南部", "counties": ["嘉義縣", "嘉義市", "臺南市", "高雄市", "屏東縣"]},
        {"region": "東部", "counties": ["花蓮縣", "臺東縣"]},
        {"region": "離島", "counties": ["澎湖縣", "金門縣", "連江縣"]},
        {"region": "全島", "counties": ["山地原住民", "平地原住民", "全國不分區", "僑居國外國民"]}
    ]
    return render(request, 'candidates/counties.html', {'ad': ad, 'regions': regions})

def districts(request, ad, county):
    districts = Terms.objects.filter(ad=ad, county=county)\
                                  .values('constituency', 'district')\
                                  .annotate(candidates=Count('id'))\
                                  .order_by('constituency')
    if len(districts) == 1:
        return HttpResponseRedirect(reverse('candidates:district', kwargs={'ad': ad, 'county': county, 'constituency': 1}))
    c = connections['default'].cursor()
    c.execute(u'''
        select data->%s->'duplicated'
        from elections_elections
        where id = '9'
    ''', [county])
    r = c.fetchone()
    duplicates = r[0] if r else []
    return render(request, 'candidates/districts.html', {'ad': ad, 'county': county, 'districts': districts, 'duplicates': duplicates})

def district(request, ad, county, constituency):
    update_at = '2016-01-17 00:00'
    if county == u'全國不分區' or county == u'僑居國外國民':
        parties = Terms.objects.filter(ad=ad, county=county, constituency=constituency).distinct('party').values_list('party', flat=True)
        party = request.GET.get('party', '')
        qs = Q(party=party) if party else Q()
        candidates = Terms.objects.select_related('latest_term', 'legislator')\
                                  .filter(Q(elected=True, ad=ad, county=county, constituency=constituency) & qs)\
                                  .extra(select={
                                      'latest_ad': "select max(ld.ad) from legislator_legislatordetail ld where id = candidates_terms.legislator_id or id = candidates_terms.latest_term_id",
                                      'legislator_uid': "select ld.legislator_id from legislator_legislatordetail ld where id = candidates_terms.legislator_id or id = candidates_terms.latest_term_id limit 1",
                                  },)\
                                  .order_by('elected', 'party', 'priority')
        return render(request, 'candidates/district_nonregional.html', {'ad': ad, 'county': county, 'candidates': candidates, 'parties': parties, 'party': party})
    else:
        county_changes = {"9": {u"桃園市": u"桃園縣"}}
        candidates_previous = Terms.objects.select_related('candidate', 'latest_term', 'legislator')\
                                           .filter(ad=int(ad)-1, county=county_changes.get(ad, {}).get(county, county), constituency=constituency)\
                                           .extra(select={
                                               'latest_ad': "select max(ld.ad) from legislator_legislatordetail ld where id = candidates_terms.legislator_id or id = candidates_terms.latest_term_id",
                                               'legislator_uid': "select ld.legislator_id from legislator_legislatordetail ld where id = candidates_terms.legislator_id or id = candidates_terms.latest_term_id limit 1",
                                           },)\
                                           .order_by('-votes')
        candidates = Terms.objects.select_related('latest_term', 'legislator')\
                                  .filter(ad=ad, county=county, constituency=constituency)\
                                  .extra(select={
                                      'latest_ad': "select max(ld.ad) from legislator_legislatordetail ld where id = candidates_terms.legislator_id or id = candidates_terms.latest_term_id",
                                      'legislator_uid': "select ld.legislator_id from legislator_legislatordetail ld where id = candidates_terms.legislator_id or id = candidates_terms.latest_term_id limit 1",
                                  },)\
                                  .order_by('-votes')
        standpoints = {}
        for term in [candidates_previous, candidates]:
            for candidate in term:
                if candidate.latest_ad > 5 and candidate.legislator_uid:
                    terms_id = tuple(LegislatorDetail.objects.filter(legislator_id=candidate.legislator_uid).values_list('id', flat=True))
                    c = connections['default'].cursor()
                    qs = u'''
                        SELECT json_agg(row)
                        FROM (
                            SELECT
                                CASE
                                    WHEN lv.decision = 1 THEN '贊成'
                                    WHEN lv.decision = -1 THEN '反對'
                                    WHEN lv.decision = 0 THEN '棄權'
                                    WHEN lv.decision isnull THEN '沒投票'
                                END as decision,
                                s.title,
                                count(*) as times
                            FROM vote_legislator_vote lv
                            JOIN standpoint_standpoint s on s.vote_id = lv.vote_id
                            WHERE lv.legislator_id in %s AND s.pro = (
                                SELECT max(pro)
                                FROM standpoint_standpoint ss
                                WHERE ss.pro > 0 AND s.vote_id = ss.vote_id
                                GROUP BY ss.vote_id
                            )
                            GROUP BY s.title, lv.decision
                            ORDER BY times DESC
                            LIMIT 3
                        ) row
                    '''
                    c.execute(qs, [terms_id])
                    r = c.fetchone()
                    standpoints.update({candidate.id: r[0] if r else []})
        return render(request, 'candidates/district.html', {'ad': ad, 'county': county, 'candidates': candidates, 'candidates_previous': candidates_previous, 'standpoints': standpoints, 'update_at': update_at})

def pc(request, candidate_id, ad):
    candidate = get_object_or_404(Terms, candidate_id=candidate_id, ad=ad)
    return render(request, 'candidates/pc.html', {'candidate': candidate})

candidates/templates/candidates/counties.html
{% extends "base.html" %}
{% load ly_extras %}

{% block title %}
    <title>立委投票指南: {{ad|ad_year}}候選人</title>
    <meta property="og:title" content="立委投票指南: {{ad|ad_year}}候選人"/>
    <meta itemprop="name" content="立委投票指南: {{ad|ad_year}}候選人">
    <link href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/0.16.1/css/semantic.min.css" rel="stylesheet">
    <script src="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/0.16.1/javascript/semantic.min.js"></script>
{% endblock title %}

{% block right %}
    <div class="hero-unit span12 hidden-phone" style="margin-left: 1%;">
        <img src="https://s3-ap-southeast-1.amazonaws.com/councilor.tw/logo.png" alt="" class="pull-right"></img>
        <h2>{{ad|ad_year}}</h2>
        <p>減少盲目投票，讓民主社會的台灣更進步</p>
    </div>
    <div class="four column doubling ui grid">
        {% for region in regions %}
            {% for county in region.counties %}
                <div class="column direct-container">
                <a href="{% url 'candidates:districts' county=county ad=ad %}" class="direct-item council-light {% cycle 'council-lightyellow' 'council-yellow' %}">
                    <img class="" src="https://s3-ap-southeast-1.amazonaws.com/councilor.tw/county-logo/{{county}}.png">
                    <div></div>
                    <br>
                    <br>
                    <div class="direct-sub right">
                            <h4>{{county}}</h4>
                    </div>
                </a>
                </div>
            {% endfor %}
            <hr>
        {% endfor %}
        </div>
    </div>
    <div id="disqus_thread"></div>
{% endblock right %}

{% block script %}
    <script>
        $(document).ready( function() {
            $('#candidates').addClass('active');
        });
    </script>
{% endblock script %}

candidates/templates/candidates/district_nonregional.html
{% extends "base.html" %}
{% load ly_extras %}

{% block title %}
    <title>立委投票指南: {{ad|ad_year}} {{county}} - {{candidates.0.district}}候選人</title>
    <meta property="og:title" content="立委投票指南: {{ad|ad_year}}{{county}} - {{candidates.0.district}}候選人"/>
    <meta itemprop="name" content="立委投票指南: {{ad|ad_year}}{{county}} - {{candidates.0.district}}候選人">
{% endblock title %}

{% block right %}
    <div class="description span12 hidden-phone">
        <h3>{{ad|ad_year}} {{county}} - {{candidates.0.district}} {{party}} 候選人
        <a class="pull-right" href="{% url 'candidates:districts' county=county ad=ad %}">☞ 其他選區</a>
        </h3>
    </div>
    <div class="row-fluid" style="padding-bottom: 24px;">
        {% if candidates %}
        <div class="btn-group">
            <a class="btn btn-inverse dropdown-toggle" href="#" data-toggle="dropdown">找單一政黨 <i class="fa fa-angle-down"></i></a>
            <ul class="dropdown-menu">
            {% for party in parties %}
                <li><a href="{% url 'candidates:district' county='全國不分區' ad=ad constituency=1 %}?party={{party}}">{{party}}</a></li>
            {% endfor %}
            </ul>
        </div>
        <table class="table table-bordered table-condensed table-striped sortable" >
            <thead>
                <tr style="font-weight:bold; background-color: #9F0050;">
                    <th colspan="11" class="lead" style="color: #eeeeee; padding-top: 10px; padding-bottom: 10px">{{ad|ad_year:1}} 立委候選人</th>
                </tr>
                <tr style="font-weight:bold;background-color: #E1D0D0;">
                    <th>當選註記</th>
                    <th>候選人</th>
                    <th>黨籍</th>
                    <th>順位</th>
                    <th>年齡</th>
                    <th>最近任期</th>
                    <th>主提案數 / 參與提案數</th>
                    <th>投票缺席率（%）</th>
                    <th>院會缺席次數</th>
                    <th>財產申報</th>
                    <th>議員資料</th>
                </tr>
            </thead>
            <tbody>
                {% for candidate in candidates %}
                    <tr style="background-color: {% cycle 'gainsboro' 'white' %};">
                        <td style="text-align:center; vertical-align:middle;">
                            {% if candidate.elected %}
                                <span class="badge badge-warning">◎</span>
                            {% endif %}
                        </td>
                        <td style="text-align:center; vertical-align:middle;"><a href=".#{{candidate.name}}">{{candidate.name}}</a></td>
                        <td style="text-align:center; vertical-align:middle;">{{candidate.party}}</td>
                        <td style="text-align:center; vertical-align:middle;">{{candidate.priority}}</td>
                        <td style="text-align:center; vertical-align:middle;">{{candidate.candidate.birth|age}}</td>
                        {% if candidate.latest_term_id %}
                        <td style="text-align:center; vertical-align:middle;">
                        {{candidate.latest_term.term_start|date:"Y"}}~
                        {% if candidate.latest_term.term_end.date %}
                        {{candidate.latest_term.term_end.date|year_tmp}}
                        {% endif %}
                        {% if candidate.latest_term.ad > 7 %}
                            <a href="{% url 'legislator:platformer_detail' legislator_id=candidate.latest_term.legislator_id ad=candidate.latest_term.ad %}"><br>（當時競選政見）</a>
                        {% endif %}
                        </td>
                        <td style="text-align:center; vertical-align:middle;">
                        {% if candidate.latest_term.ad > 7 %}
                            {{candidate.latest_term.bill_param.sponsor}}
                            <a href="{% url 'legislator:biller_detail' legislator_id=candidate.latest_term.legislator_id ad=candidate.latest_term.ad %}"><br>（看提案）</a>
                        {% endif %}
                        </td>
                        <td style="text-align:center; vertical-align:middle;">
                        {% if candidate.latest_term.ad > 5 %}
                            {{candidate.latest_term.vote_param.not_voting}} 次<br>（投票缺席率{{candidate.latest_term.vote_param.not_voting|divide:candidate.latest_term.vote_param.total}} %）
                            <a href="{% url 'legislator:voter_standpoints' legislator_id=candidate.latest_term.legislator_id ad=candidate.latest_term.ad %}"><br>（看表決）</a>
                        {% endif %}
                        </td>
                        <td style="text-align:center; vertical-align:middle;">
                        {% if candidate.latest_term.ad > 5 %}
                            {{candidate.latest_term.attendance_param.absent}} 次<br>（缺席率{{candidate.latest_term.attendance_param.absent|divide:candidate.latest_term.attendance_param.total}} %）
                        {% endif %}
                        </td>
                        <td style="text-align:center; vertical-align:middle;">
                            <a href="http://sunshine.cy.g0v.tw/people/{{candidate.name}}/property/overview/" target="_blank">{{candidate.name}}</a>
                        </td>
                        {% else %}
                        <td colspan="5" style="text-align:center; vertical-align:middle;">
                        {% if candidate.cec_data.drawno %}
                        未擔任過立委，所以沒有過去紀錄，可參考下方<a href=".#{{candidate.name}}">學經歷、政見</a>等資訊
                        {% endif %}
                        </td>
                        {% endif %}

                        {% if candidate.councilor %}
                        <td style="text-align:center; vertical-align:middle;">
                            {% if candidate.councilor.elected %}
                            <span class='badge badge-success'><h4>現任議員</h4></span>
                            {% endif %}
                            <a href="http://councils.g0v.tw/candidates/2014/{{candidate.councilor.county}}/{{candidate.councilor.constituency}}/" target="_blank">參選{{candidate.councilor.county}}議員紀錄</a>
                        </td>
                        {% else %}
                        <td></td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
        {% if candidates.0.cec_data.drawno %}
        <br>
        <div >
            {% for candidate in candidates %}
            <div class="row" id="{{candidate.name}}">
                <div class="span4">
                    <h4>
                        <span class='badge badge-success'>順位 {{candidate.priority}}</span>
                        {{candidate.name}}&nbsp;
                        <a href=".#{{candidate.name}}"><i class="fa fa-link"></i></a>
                    </h4>
                    <div class="text-center"><img class="candidate-photo" src="http://g0v-data.github.io/cec-crawler/images/{{candidate.cec_data.cityno}}-{{candidate.cec_data.cityname|urlencode}}-{{candidate.cec_data.sessionname|urlencode}}-{{candidate.cec_data.drawno}}-{{candidate.cec_data.candidatename|urlencode}}.jpg"></div>
                    <div class="property-header">黨籍</div>
                    <div class="property-body">{{candidate.party}}</div>
                    <div class="property-header">出生地</div>
                    <div class="property-body">{{candidate.cec_data.placecityname}}</div>
                    <div class="property-header">學歷</div>
                    <div class="property-body">{{candidate.cec_data.rptedu|safe|linebreaks}}</div>
                    <div class="property-header">經歷</div>
                    <div class="property-body">{{candidate.cec_data.rptexp|safe|linebreaks}}</div>
                </div>
                <div class="span8">
                    <h4 class="political-opinion-header">政見</h4>
                    <div class="political-opinion-body">
                        {{candidate.cec_data.politics|safe|linebreaks}}
                    </div>
                </div>
            </div>
            <hr class="candidates-separator">
            {% endfor %}
        </div>
        {% endif %}
        <div id="disqus_thread"></div>
    </div>
{% endblock right %}

candidates/templates/candidates/district_result.html
{% extends "base.html" %}
{% load ly_extras %}

{% block title %}
    <title>立委投票指南: {{ad|ad_year}} {{county}} - {{candidates.0.district}}候選人</title>
    <meta property="og:title" content="立委投票指南: {{ad}}{{county}} - {{candidates.0.district}}候選人"/>
    <meta itemprop="name" content="立委投票指南: {{ad}}{{county}} - {{candidates.0.district}}候選人">
{% endblock title %}

{% block right %}
    <div class="description span12 hidden-phone" style="margin-left: 0px;">
        <h3>{{ad|ad_year}} {{county}} - {{candidates.0.district}} 候選人</h3>
        <font class="span8"><a href="{% url 'candidates:districts' county=county ad=ad %}">☞ 其他選區</a></font>

    </div>
    <div class="row-fluid" style="padding-bottom: 24px;">
        {% if candidates %}
        <table class="table table-bordered table-condensed table-striped sortable" >
            <thead>
                <tr style="font-weight:bold;background-color: #E1D0D0;">
                    <th rowspan="2">當選註記</th>
                    <th rowspan="2">表決立場</th>
                    <th rowspan="2">候選人</th>
                    <th rowspan="2">黨籍</th>
                    <th rowspan="2">性別</th>
                    <th rowspan="2">出生年次</th>
                    <th rowspan="2">選前最近任期</th>
                    <th rowspan="2">得票數</th>
                    <th rowspan="2">得票率</th>
                    <th colspan="3">競選政治獻金</th>
                    <th rowspan="2">財產申報</th>
                </tr>
                <tr style="background-color: #CCFFCC;">
                    <th>收入</th>
                    <th>支出</th>
                    <th>餘額</th>
                    </tr>
                </tr>
            </thead>
            <tbody>
                {% for candidate in candidates_previous %}
                    <tr style="background-color: {% cycle 'gainsboro' 'white' %};">
                        <td style="text-align:center; vertical-align:middle;">
                            {% if candidate.elected %}
                                <span class="badge badge-warning">*</span>
                            {% endif %}
                        </td>
                        <td style="vertical-align:middle;">
                            {% with sp=standpoints|json_lookup:candidate.id %}
                            {% if sp %}
                                {% for standpoint in sp %}
                                    {{standpoint.title}}：{{standpoint.times}}次{{standpoint.decision}}<br>
                                {% endfor %}
                                <a href="{% url 'legislator:voter_standpoints' legislator_id=candidate.legislator_uid ad=candidate.latest_ad %}" >其他...</a>
                            {% endif %}
                            {% endwith %}
                        </td>
                        <td style="text-align:center; vertical-align:middle;">
                            {% if candidate.legislator_uid %}
                                {% if candidate.latest_ad > 5 %}
                                    <a href="{% url 'legislator:voter_standpoints' legislator_id=candidate.legislator_uid ad=candidate.latest_ad %}">{{candidate.name}}</a>
                                {% else %}
                                    <a href="{% url 'legislator:info' legislator_id=candidate.legislator_uid ad=candidate.latest_ad %}">{{candidate.name}}</a>
                                {% endif %}
                            {% else %}
                                {{candidate.name}}
                            {% endif %}
                        </td>
                        <td style="text-align:center; vertical-align:middle;">
                            {{candidate.party}}
                        </td>
                        <td style="text-align:center; vertical-align:middle;">
                            {{candidate.gender}}
                        </td>
                        <td style="text-align:center; vertical-align:middle;">
                            {{candidate.birth|date:"Y"}}
                        </td>
                        <td style="text-align:center; vertical-align:middle;">
                            {% if candidate.latest_term_id %}
                                {{candidate.latest_term.ad|ad_year}}
                                {% if candidate.latest_term.ad > 7 %}
                                    <a href="{% url 'legislator:platformer_detail' legislator_id=candidate.latest_term.legislator_id ad=candidate.latest_term.ad %}"><br>（當時競選政見）</a>
                                {% endif %}
                            {% endif %}
                        </td>
                        <td style="text-align:center; vertical-align:middle;">
                            {{candidate.votes}}
                        </td>
                        <td style="text-align:center; vertical-align:middle;">
                            {% widthratio candidate.votes_percentage 1 100 %} ％
                        </td>
                        <td style="text-align:center; vertical-align:middle;">
                            {% if candidate.politicalcontributions %}
                                <a href="{% url 'candidates:political_contributions' id=candidate.id %}#d3_in"><font class="price">{{candidate.politicalcontributions.in_total}}</font></a>
                            {% endif %}
                        </td>
                        <td style="text-align:center; vertical-align:middle;">
                            {% if candidate.politicalcontributions %}
                                <a href="{% url 'candidates:political_contributions' id=candidate.id %}#d3_out"><font class="price">{{candidate.politicalcontributions.out_total}}</font></a>
                            {% endif %}
                        </td>
                        <td style="text-align:center; vertical-align:middle;">
                            {% if candidate.politicalcontributions %}
                                <font class="price">{{candidate.politicalcontributions.balance}}</font>
                            {% endif %}
                        </td>
                        <td style="text-align:center; vertical-align:middle;">
                            {% if candidate.legislator_uid %}
                                <a href="http://sunshine.cy.g0v.tw/people/{{candidate.name}}/property/overview/" target="_blank">{{candidate.name}}</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
{% endblock right %}

{% block script %}
    <script src="https://s3-ap-northeast-1.amazonaws.com/twly.tw/zhutil.min.js"></script>
    <script>
        $('.price').each(function(index,ele){
            var number = $(ele).text()
            zh_number = zhutil.approximate(number, {base: '萬', extra_decimal: 0});
            $(ele).replaceWith(zh_number)
        })
    </script>
{% endblock script %}