bill/urls.py
from django.conf.urls import url
from bill import views

urlpatterns = [
    url(r'^$', views.bills, name='bills'),
    url(r'^(?P<bill_id>\S+)/$', views.bill, name='bill'),
]

candidates/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from candidates import views

urlpatterns = [
    url(r'^$', views.counties, {"ad": 9}),
    url(r'^(?P<ad>\d+)/(?P<county>\S+)/(?P<constituency>\d+)/$', views.district, name='district'),
    url(r'^(?P<ad>\d+)/(?P<county>\S+)/$', views.districts, name='districts'),
    url(r'^(?P<ad>\d+)/$', views.counties, name='counties'),
    url(r'^pc/(?P<candidate_id>\S+)/(?P<ad>\d+)/$', views.pc, name='pc'),
]

legislator/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from legislator import views

ad = 9
urlpatterns = [
    url(r'^(?P<index>conflict|not_voting)/(?P<ad>[1-9])/$', views.index, name='index'),
    url(r'^(?P<index>conflict|not_voting)/$', views.index, {'ad': ad}, name='index'),
    url(r'^counties/(?P<ad>\d+)/$', views.counties, name='counties'),
    url(r'^counties/$', views.counties, {'ad': ad}, name='counties'),
    url(r'^county/(?P<county>.+)/(?P<ad>\d+)/$', views.county, name='county'),
    url(r'^county/(?P<county>.+)/$', views.county, {'ad': ad}, name='county'),
    url(r'^committee/(?P<committee>.+)/(?P<ad>\d+)/$', views.committee, name='committee'),
    url(r'^committee/(?P<committee>.+)/$', views.committee, {'ad': ad}, name='committee'),
    url(r'^info/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.info, name='info'),
    url(r'^voter_sp/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.voter_standpoints, name='voter_standpoints'),
    url(r'^voter/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.voter_detail, name='voter_detail'),
    url(r'^biller/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.biller_detail, name='biller_detail'),
    url(r'^pc/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.personal_political_contributions, name='personal_political_contributions'),
    url(r'^platformer/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.platformer_detail, name='platformer_detail'),
    url(r'^report/(?P<index>biller|conscience_vote|vote|ly)/(?P<ad>\d+)/$', views.chart_report, name='chart_report'),
    url(r'^report/(?P<index>biller|conscience_vote|vote|ly)/$', views.chart_report, {'ad': ''}, name='chart_report'),
    url(r'^report/political_contributions/(?P<index>\S+)/(?P<compare>\S+)/(?P<party>\S+)/$', views.political_contributions_report, name='political_contributions_report'),
]

ly/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.conf import settings
from rest_framework import routers

from . import views as ly_views
from api import views as api_views

#--> rest framework url
router = routers.DefaultRouter()
router.register(r'legislator', api_views.LegislatorViewSet)
router.register(r'legislator_terms', api_views.LegislatorDetailViewSet)
router.register(r'committees', api_views.CommitteesViewSet)
router.register(r'legislator_committees', api_views.Legislator_CommitteesViewSet)
router.register(r'sittings', api_views.SittingsViewSet)
router.register(r'vote', api_views.VoteViewSet)
router.register(r'legislator_vote', api_views.Legislator_VoteViewSet)
router.register(r'bill', api_views.BillViewSet)
router.register(r'law', api_views.LawViewSet)
router.register(r'legislator_bill', api_views.Legislator_BillViewSet)
router.register(r'attendance', api_views.AttendanceViewSet)
router.register(r'candidates', api_views.CandidatesViewSet)
router.register(r'candidates_terms', api_views.Candidates_TermsViewSet)
router.register(r'standpoint', api_views.StandpointViewSet)
#<--
urlpatterns = [
    url(r'^$', ly_views.home, name='home'),
    url(r'^legislator/', include('legislator.urls', namespace="legislator")),
    url(r'^candidates/', include('candidates.urls', namespace="candidates")),
    url(r'^vote/', include('vote.urls', namespace="vote")),
    url(r'^bill/', include('bill.urls', namespace="bill")),
    url(r'^about/$', ly_views.about, name='about'),
    url(r'^reference/$', ly_views.reference, name='reference'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^accounts/logout/$', ly_views.logout, name='logout'),
    url(r'^api/', include(router.urls)),
]

bill/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.postgres.fields import JSONField


class Bill(models.Model):
    proposer = models.ManyToManyField('legislator.LegislatorDetail', through='Legislator_Bill')
    uid = models.TextField(primary_key=True)
    ad = models.IntegerField(db_index=True, )
    data = JSONField(null=True)
    for_search = models.TextField(null=True)
    def __unicode__(self):
        return self.uid

class Legislator_Bill(models.Model):
    legislator = models.ForeignKey('legislator.LegislatorDetail', related_name='bills')
    bill = models.ForeignKey(Bill)
    role = models.CharField(max_length=32, db_index=True, )

    class Meta:
        unique_together = ("legislator", "bill")

class Law(models.Model):
    bill = models.ForeignKey(Bill, null=True, related_name='laws')
    uid = models.TextField(primary_key=True)
    ad = models.IntegerField(db_index=True, )
    data = JSONField(null=True)
    def __unicode__(self):
        return self.uid

bill/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from haystack.query import SearchQuerySet

from .models import Bill, Law
from commontag.views import paginate
from search.views import keyword_list


def bills(request):
    if request.GET.get('keyword'):
        bills_uid = [x.uid for x in SearchQuerySet().filter(content=request.GET['keyword']).models(Bill)]
        bills = Bill.objects.filter(uid__in=bills_uid).prefetch_related('laws').order_by('-uid')
    else:
        bills = Bill.objects.all().prefetch_related('laws').order_by('-uid')
    bills = paginate(request, bills)
    keywords = keyword_list(3)
    get_params = '&'.join(['%s=%s' % (x, request.GET[x]) for x in ['keyword'] if request.GET.get(x)])
    return render(request, 'bill/bills.html', {'bills': bills, 'keyword_obj': keywords, 'hot_keyword': keywords[:5], 'keyword': request.GET.get('keyword', ''), 'get_params': get_params})

def bill(request, bill_id):
    law = get_object_or_404(Law.objects.select_related('bill'), bill_id=bill_id)
    return render(request, 'bill/law.html', {'law': law, })

templates/common/bills.html
{% load ly_extras %}
{% load highlight %}

<ul class="media-list">
    {% for fragment in bills %}
    <li class="media">
        <div class="media-body well">
            <h5 class="text-success">立法理由</h5>
            <div class="media-heading">
                {% if keyword %}
                    {{fragment.proposed_by}}
                    <small class="muted">（略）</small>
                    {% highlight fragment.text with keyword %}
                {% else %}
                    {{fragment.abstract}}
                {% endif %}
            </div>
            <div>
                <h5 class="text-success">進展</h5>
                <blockquote>
                    {% if fragment.rejected_times != 0 %}
                    <span class="label label-warning"><font class="lead">總共被退回程序委員會{{fragment.rejected_times}}次</font></span>
                    {% endif %}
                    {% for progress, date in fragment.progress_history %}
                    <i class="icon-ok"></i> {{progress}}<font class="muted">（{{date}}）</font>
                    {% endfor %}
                </blockquote>
            </div>
            <h4>
                <a href="{{ "http://ly.g0v.tw/bills/"|add:fragment.uid }}" target="_blank">☞ 查看法條修正對照表</a>
            </h4>
        </div>
    </li>
    {% endfor %}
</ul>

templates/common/color_info_of_party.html
<tfoot>
<tr class="info" >
    <td colspan="{{ column }}" style="text-align:center;">#註：
        <font color=0033FF>中國國民黨</font>&nbsp;-&nbsp;<font color=009900>民主進步黨</font>&nbsp;-&nbsp;
        <font color=FF6600>親民黨</font>&nbsp;-&nbsp;<font color=FFCC00>新黨</font>&nbsp;-&nbsp;<font color=brown>台灣團結聯盟</font>&nbsp;-&nbsp;
        <font color=FF00FF>無黨團結聯盟</font>&nbsp;-&nbsp;<font color=330066>民國黨</font>&nbsp;-&nbsp;<font color=777777>無黨籍</font>
    </td>
</tr>
</tfoot>

templates/common/d3_chart.html
{% load ly_extras %} 
<style>

.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

.bar {
  fill: red;
}

.bar:hover {
  fill: orangered ;
}
.bar_compare {
  fill: orange;
}

.bar_compare:hover {
  fill: orangered ;
}

.line {
  fill: none;
  stroke: steelblue;
  stroke-width: 1.5px;
}

.x.axis path {
  display: none;
}

.d3-tip {
  line-height: 1;
  font-weight: bold;
  padding: 12px;
  background: rgba(0, 0, 0, 0.8);
  color: #fff;
  border-radius: 2px;
}

/* Creates a small triangle extender for the tooltip */
.d3-tip:after {
  box-sizing: border-box;
  display: inline;
  font-size: 10px;
  width: 100%;
  line-height: 1;
  color: rgba(0, 0, 0, 0.8);
  content: "\25BC";
  position: absolute;
  text-align: center;
}

/* Style northward tooltips differently */
.d3-tip.n:after {
  margin: -1px 0 0 0;
  top: 100%;
  left: 0;
}
</style>
<script src="https://s3-ap-northeast-1.amazonaws.com/twly.tw/d3.min.js"></script>
<script src="http://labratrevenge.com/d3-tip/javascripts/d3.tip.min.js"></script>
<script> 

var data = {{data|as_json}}

{% if compare %}
var compare = {{compare}}
{% endif %}

var margin = {top: 20, right: 80, bottom: 120, left: 80},
    width = 480 - margin.left - margin.right,
    height = 360 - margin.top - margin.bottom;

var formatPercent = d3.format(".0%");

var x = d3.scale.ordinal()
    .rangeRoundBands([0, width], .1);

var y = d3.scale.linear()
    .range([height, 0]);

var yRight = d3.scale.linear()
    .domain([0, 1])
    .range([height, 0]);

var xAxis = d3.svg.axis()
    .scale(x)
    .orient("bottom");

var yAxis = d3.svg.axis()
    .scale(y)
    .orient("left")

var yAxisRight = d3.svg.axis()
    .scale(yRight)
    .ticks(10)
    .orient("right")
    .tickFormat(d3.format("%"));

var tip_compare = d3.tip()
  .attr('class', 'd3-tip')
  .offset([-10, 0])
  .html(function(d) {
{% if compare %}
    {% if index == 'biller' or index == 'proposal' %}
        return "<strong>平均</strong> ：<span style='color:red'>" + compare + "</span>次提案";
    {% elif index == 'vote' or index == 'ly' %}
        return "<strong>" + d.name + "</strong> ：實到<span style='color:red'>" + (compare-d.totalNum) + "</span>次";
    {% else %}
        {% if index == 'conscience_vote' %}
            return "<strong>" + d.name + "</strong> ：隨黨投票<span style='color:red'>" + (compare-d.totalNum) + "</span>次";
        {% elif index == 'attend_committee' %}
            return "<strong>平均</strong> ：<span style='color:red'>" + compare + "</span>次列席";
        {% endif %}
    {% endif %}
{% endif %}
  });

var tip = d3.tip()
  .attr('class', 'd3-tip')
  .offset([-10, 0])
  .html(function(d) {
{% if index == 'biller' or index == 'proposal' %}
    return "<strong>" + d.name + "</strong> ：<span style='color:red'>" + d.totalNum + "</span>次提案";
{% elif index == 'vote' or index == 'ly' or index == 'committee' %}
    return "<strong>" + d.name + "</strong> ：缺席<span style='color:red'>" + d.totalNum + "</span>次";
{% else %}
    {% if index == 'conscience_vote' %}
        return "<strong>" + d.name + "</strong> ：脫黨投票<span style='color:red'>" + d.totalNum + "</span>次";
    {% elif index == 'attend_committee' %}
        return "<strong>" + d.name + "</strong> ：<span style='color:red'>" + d.totalNum + "</span>次列席";
    {% endif %}
{% endif %}
  });

var svg = d3.select("#d3").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
    .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

svg.call(tip);
svg.call(tip_compare);

x.domain(data.map(function(d) { return d.name; }));
{% if index == 'biller' or index == 'proposal' or index == 'committee' or index == 'attend_committee' %}
    y.domain([0, d3.max(data, function(d) { return d.totalNum; })]);
{% else %}
    y.domain([0, compare]);
{% endif %}

svg.append("g")
    .attr("class", "x axis")
    .attr("transform", "translate(0," + height + ")")
    .call(xAxis)
    .selectAll("text")  
        .style("text-anchor", "end")
        .attr("transform", function(d) {
            return "rotate(-45)" 
        });

svg.append("g")
    .attr("class", "y axis")
    .call(yAxis)
    .append("text")
    .attr("transform", "rotate(-90)")
    .attr("dy", "-3em")
    .style("text-anchor", "end")
    .text("(次)");

svg.append("g")
    .attr("class", "y axis")
    .attr("transform", "translate(" + (width) + ",0)")
    .call(yAxisRight);

var legislator = svg.selectAll(".legislator")
    .data(data);

var barGroup = legislator.enter().append("g")
    .attr("class", "g")
    .attr("transform", function(d) { return "translate(" + x(d.name) + ",0)"; });

barGroup.append("rect")
    .attr("class", "bar")
    .attr("width", x.rangeBand())
    .attr("y", function(d) { return y(d.totalNum); })
    .attr("height", function(d) { return height - y(d.totalNum); })
    .on('mouseover', tip.show)
    .on('mouseout', tip.hide);

{% if compare %}
    barGroup.append("rect")
        .attr("class", "bar_compare")
        .attr("width", x.rangeBand())
    {% if index == 'biller' or index == 'proposal' or index == 'attend_committee' %}
        .attr("y", function(d) { return y(compare); })
        .attr("height", function(d) { return height - y(compare); })
    {% else %}
        .attr("y", function(d) { return 0; })
        .attr("height", function(d) { return y(d.totalNum); })
    {% endif %}
        .on('mouseover', tip_compare.show)
        .on('mouseout', tip_compare.hide);
{% endif %}

var legend = svg.select(".barGroup:last-child").selectAll(".legend")
    .enter().append("g")
    .attr("class", "g")
    .attr("transform", function(d) { return "translate(" + x.rangeBand() / 2 + "," + y(d.totalNum / 2) + ")"; });

legend.append("line")
    .attr("x2", 10);

legend.append("text")
    .attr("x", 13)
    .attr("dy", ".35em")
    .text(function(d) { return d.name; });

</script>

templates/common/highlight.html
{% load ly_extras %}
<form class="form-inline">
    <select id='county'>
        <option value="">標註選區</option>
        {% for fragment in ad|distinct_county %}
        <option value="{{fragment}}">{{fragment}}</option>
        {% endfor %}
    </select>
    <select id='gender'>
        <option value="">標註性別</option>
        <option value="男">男</option>
        <option value="女">女</option>
    </select>
</form>

templates/common/keyword_auto_complete.html
{% load ly_extras %}

<link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script>
    $(function() {
        var availableTags = {{keyword_obj|as_json}};
        $("#keyword").autocomplete({
            source: availableTags,
            select: function(event, ui) {
                $(event.target).val(ui.item.value);
                $('#form').submit();
                return false;
            }
        });
        {% if names %}
            var availableNames = {{names|as_json}};
            $("#name").autocomplete({
                source: availableNames,
                select: function(event, ui) {
                    $(event.target).val(ui.item.value);
                    $('#form-name').submit();
                    return false;
                }
            });
        {% endif %}
    });
</script>

templates/common/ly_color_by_party.html
{% spaceless %}
{% if party == "中國國民黨" %}
<font color=0033FF>
{% elif party == "民主進步黨" %}
<font color=009900>
{% elif party == "親民黨" %}
<font color=FF6600>
{% elif party == "臺灣團結聯盟" %}
<font color=brown>
{% elif party == "無黨團結聯盟" %}
<font color=FF00FF>
{% elif party == "無黨籍" %}
<font color=777777>
{% elif party == "民國黨" %}
<font color=330066>
{% elif party == "新黨" %}
<font color=FFCC00>
{% else %}
<font>
{% endif %}
{{ ly.name|truncatechars:6 }}</font>
{% endspaceless %}

templates/common/ly_info.html
{% extends "base.html" %}
{% load staticfiles %}
{% load ly_extras %}

{% block title %}
{% endblock title %}

{% block right %}
    {% block top-menu %}
    {% endblock top-menu %}
    <div class="row-fluid">
        <div id="sidebar-left" class="span2">
            <div class="nav-collapse sidebar-nav">
                <ul class="nav nav-tabs nav-stacked">
                    <p class="lead">{{ ly.name }}</p>
                    <img src="{{ly.image}}" width="50%">
                    <li id='url_info'><a href="{% url 'legislator:info' legislator_id=ly.legislator_id ad=ly.ad %}"><i class="fa fa-info"> 基本資料</i></a></li>
                    <li id='url_property'><a href="http://sunshine.cy.g0v.tw/people/{{ly.name}}/property/overview/" target="_blank"><i class="fa fa-bank"> 個人財產申報</i></a></li>
                    <li id='url_vote'><a href="{% url 'legislator:voter_standpoints' legislator_id=ly.legislator_id ad=ly.ad %}"><i class="fa fa-balance-scale"> 表決</i></a></li>
                    {% if ly.elected_candidate %}
                    <li id='url_polticalcontributions'><a href="{% url 'candidates:pc' candidate_id=ly.elected_candidate.candidate_id ad=ly.ad %}"><i class="fa fa-dollar"> 政治獻金</i></a></li>
                    {% endif %}
                    <li id='url_bill'><a href="{% url 'legislator:biller_detail' legislator_id=ly.legislator_id ad=ly.ad %}"><i class="fa fa-book"> 法條修正案</i></a></li>
                    <li id='url_politics'><a href="{% url 'legislator:platformer_detail' legislator_id=ly.legislator_id ad=ly.ad %}"><i class="fa fa-comment"> 競選政見</i></a></li>
                </ul>
            </div>
            <br>
        </div>
        <div id="content" class="span10" style="min-height: 700px; padding-bottom: 150px;">
            {% block ly_detail %}
            {% endblock ly_detail %}
            <hr>
            <div id="disqus_thread"></div>
        </div>
    </div>
{% endblock right %}

templates/common/pagination.html
<div class="pagination" align="center">
    <span class="step-links">
        {% if items.has_previous %}
            {% if keyword %}
            <a href="?{{get_params}}&page={{ items.previous_page_number }}">上一頁</a>
            {% else %}
            <a href="?page={{ items.previous_page_number }}">上一頁</a>
            {% endif %}
        {% endif %}

        <span class="current">
            這是第{{ items.number }}頁（共{{ items.paginator.num_pages }}頁）
        </span>

        {% if items.has_next %}
            {% if keyword %}
            <a href="?{{get_params}}&page={{ items.next_page_number }}">下一頁</a>
            {% else %}
            <a href="?page={{ items.next_page_number }}">下一頁</a>
            {% endif %}
        {% endif %}
    </span>
</div>

templates/common/search_keyword_form.html
<form action="" method="get" class="form-inline" id="form">
    <br>
    <fieldset>
        <div class="input-append">
            <input type="search" name="keyword" id="keyword" class="span9" maxlength="20" placeholder="{{placeholder_text}}" value="{{keyword}}">
            <button type="submit" class="btn btn-moonc">搜尋</button>
        </div>
        {% if advance_search %}
            {% include advance_search %}
        {% endif %}
    </fieldset>
</form>

templates/common/search_name_form.html
<form action="" method="get" class="form-inline" id="form-name">
    <br>
    <fieldset>
        <div class="input-append">
            <input type="search" name="name" id="name" class="span9" maxlength="10" placeholder="{{placeholder_text}}">
            <button type="submit" class="btn btn-moonc">搜尋</button>
        </div>
    </fieldset>
</form>

templates/common/sorttable.html
<style>
    table.sortable th:not(.sorttable_sorted):not(.sorttable_sorted_reverse):after {
        content: " \25B4\25BE"
    }
</style>
<script src="https://s3-ap-northeast-1.amazonaws.com/twly.tw/sorttable.js"></script>

templates/common/sponsor.html
<ul>
{% for element in list %}
    <li data-toggle="collapse" data-target="#ref_bill_{{role}}_{{element.party}}"><span>{{element.party}}：{{element.legislators|length}}人 <i class="fa fa-caret-square-o-down"></i></span></li>
    <div id="ref_bill_{{role}}_{{element.party}}" class="collapse">
        <ul class="inline">
        {% for ly in element.legislators %}
            <li><a href="{% url 'legislator:voter_standpoints' legislator_id=ly.legislator_id ad=law.ad %}">{{ly.name}}</a></li>
        {% endfor %}
        </ul>
    </div>
    <br>
{% endfor %}
</ul>

templates/common/vote_conscience_checkbox.html
<a data-toggle="collapse" data-target="#advanced_search">進階</a>
<div id="advanced_search" class="collapse in">
    <input type="checkbox" name="conscience" id="conscience"> 脫黨投票的表決
    <input type="checkbox" name="has_tag" id="has_tag"> 有網友標籤的表決
</div>