bill/urls.py
from django.conf.urls import url
from bill import views

urlpatterns = [
    url(r'^$', views.bills, name='bills'),
    url(r'^(?P<bill_id>\S+)/$', views.bill, name='bill'),
]

candidates/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from candidates import views

urlpatterns = [
    url(r'^$', views.counties, {"ad": 9}),
    url(r'^(?P<ad>\d+)/(?P<county>\S+)/(?P<constituency>\d+)/$', views.district, name='district'),
    url(r'^(?P<ad>\d+)/(?P<county>\S+)/$', views.districts, name='districts'),
    url(r'^(?P<ad>\d+)/$', views.counties, name='counties'),
    url(r'^pc/(?P<candidate_id>\S+)/(?P<ad>\d+)/$', views.pc, name='pc'),
]

legislator/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from legislator import views

ad = 9
urlpatterns = [
    url(r'^(?P<index>conflict|not_voting)/(?P<ad>[1-9])/$', views.index, name='index'),
    url(r'^(?P<index>conflict|not_voting)/$', views.index, {'ad': ad}, name='index'),
    url(r'^counties/(?P<ad>\d+)/$', views.counties, name='counties'),
    url(r'^counties/$', views.counties, {'ad': ad}, name='counties'),
    url(r'^county/(?P<county>.+)/(?P<ad>\d+)/$', views.county, name='county'),
    url(r'^county/(?P<county>.+)/$', views.county, {'ad': ad}, name='county'),
    url(r'^committee/(?P<committee>.+)/(?P<ad>\d+)/$', views.committee, name='committee'),
    url(r'^committee/(?P<committee>.+)/$', views.committee, {'ad': ad}, name='committee'),
    url(r'^info/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.info, name='info'),
    url(r'^voter_sp/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.voter_standpoints, name='voter_standpoints'),
    url(r'^voter/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.voter_detail, name='voter_detail'),
    url(r'^biller/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.biller_detail, name='biller_detail'),
    url(r'^pc/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.personal_political_contributions, name='personal_political_contributions'),
    url(r'^platformer/(?P<legislator_id>\d+)/(?P<ad>\d+)/$', views.platformer_detail, name='platformer_detail'),
    url(r'^report/(?P<index>biller|conscience_vote|vote|ly)/(?P<ad>\d+)/$', views.chart_report, name='chart_report'),
    url(r'^report/(?P<index>biller|conscience_vote|vote|ly)/$', views.chart_report, {'ad': ''}, name='chart_report'),
    url(r'^report/political_contributions/(?P<index>\S+)/(?P<compare>\S+)/(?P<party>\S+)/$', views.political_contributions_report, name='political_contributions_report'),
]

ly/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.conf import settings
from rest_framework import routers

from . import views as ly_views
from api import views as api_views

#--> rest framework url
router = routers.DefaultRouter()
router.register(r'legislator', api_views.LegislatorViewSet)
router.register(r'legislator_terms', api_views.LegislatorDetailViewSet)
router.register(r'committees', api_views.CommitteesViewSet)
router.register(r'legislator_committees', api_views.Legislator_CommitteesViewSet)
router.register(r'sittings', api_views.SittingsViewSet)
router.register(r'vote', api_views.VoteViewSet)
router.register(r'legislator_vote', api_views.Legislator_VoteViewSet)
router.register(r'bill', api_views.BillViewSet)
router.register(r'law', api_views.LawViewSet)
router.register(r'legislator_bill', api_views.Legislator_BillViewSet)
router.register(r'attendance', api_views.AttendanceViewSet)
router.register(r'candidates', api_views.CandidatesViewSet)
router.register(r'candidates_terms', api_views.Candidates_TermsViewSet)
router.register(r'standpoint', api_views.StandpointViewSet)
#<--
urlpatterns = [
    url(r'^$', ly_views.home, name='home'),
    url(r'^legislator/', include('legislator.urls', namespace="legislator")),
    url(r'^candidates/', include('candidates.urls', namespace="candidates")),
    url(r'^vote/', include('vote.urls', namespace="vote")),
    url(r'^bill/', include('bill.urls', namespace="bill")),
    url(r'^about/$', ly_views.about, name='about'),
    url(r'^reference/$', ly_views.reference, name='reference'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^accounts/logout/$', ly_views.logout, name='logout'),
    url(r'^api/', include(router.urls)),
]

vote/urls.py
from django.conf.urls import url
from vote import views

urlpatterns = [
    url(r'^$', views.votes, name='votes'),
    url(r'^(?P<vote_id>\S+)/$', views.vote, name='vote_detail'),
]

about/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from vote.models import Vote
from proposal.models import Proposal
from bill.models import Bill

def about(request):
    nvotes = Vote.objects.count()
    nproposals = Proposal.objects.count()
    nbills = Bill.objects.count()
    return render(request,'about/about.html', {'current_url': 'http://twly.herokuapp.com'+request.get_full_path(),'nvotes':nvotes,'nproposals':nproposals,'nbills':nbills})

templates/about.html
{% extends "base.html" %}

{% block title %}
    <title>立委投票指南:關於&授權</title>
    <meta property="og:title" content="立委投票指南:關於&授權"/>
    <meta itemprop="name" content="立委投票指南:關於&授權">
{% endblock %}

{% block right %}
    <div class="row-fluid">
        <div class="span7">
            <div class="hero-unit">
            <div class="fb-like pull-right" data-width="50" data-layout="box_count" data-show-faces="false" data-send="false" href="https://www.facebook.com/TW.Voter.Guide"></div>
                <dl>
                    <dt>減少盲目投票，讓民主社會的台灣更進步</dt>
                    <p><dd>你的第一次投票經驗如何？<br>我的第一次投票是聽從大人的意見投票，投完票後我覺得不舒服，候選人我不認識，也不知道他做了什麼？
                    立場是什麼？是否有為民發聲？<br>我覺得得來不易的民主被我這種不懂的老百姓浪費了，如果民主制度是好的制度的話，它一定還少了什麼。</dd></p>
                    <dt>輸入關鍵字，關心你關心的議題</dt>
                    <p><dd>此網頁提供<a href="{% url 'bill:bills' %}">「法條修正草案」</a>、<a href="{% url 'vote:votes' %}">「立法院的投票表決」</a>等部分。<br>資訊也許不足以完全斷定一個立委的表現，但已足夠我們了解他的立場。</dd></p>
                    <dt>拋磚引玉</dt>
                    <p><dd>希望吸引更多個人、團體自發性投入，發揮各自擅長的事讓台灣更好。希望有一天台灣政府能主動提供更正確完整的此類資訊給人民。</dd></p>
                    <dt>公信力？</dt>
                    <p><dd>本站資訊皆由政府所提供的資料經由電腦程式運算產生，以維持資訊之客觀，程式開源以供檢驗。<br>
                    目前共包含「<span class="badge badge-success">{{nbills}}</span>個法條修正草案」以及「<span class="badge badge-important">{{nvotes}}</span>個立法院表決」。<br>本站非營利性質，只期許在此站孱弱的監督之下，能多喚醒立委諸公1～2%的良知。</dd></p>
                </dl>
                <button type="button" class="btn btn-danger" data-toggle="collapse" data-target="#nonresponse">免責聲明</button>
                <div id="nonresponse" class="collapse in">
                    <small>本網站所提供之網頁或資料，均為被連結網站所提供，相關權利為該等網站或合法權利人所有，本網站不擔保其正確性、即時性或完整性。<br>
                        本網站不提供任何種類的明示或暗示的保證，您於使用本網站資訊和服務時應自行評估及判斷。</small>
                </div>
            </div>
        </div>
        <div class="span5">
            <div class="hero-unit">
                <dl>
                    <dt>CC0 1.0 公眾領域貢獻宣告</dt>
                    <p><dd>作者在法律許可的範圍內，拋棄此著作依著作權法所享有之權利，包括所有相關與鄰接的法律權利，並宣告將該著作貢獻至公眾領域。<br>為避免斷章取義，片段使用本站資訊請附上本站連結，讓每個人都有機會以自己的觀點關心台灣。</dd></p>
                    <dt>程式原始碼</dt>
                    <p><dd><a href="https://github.com/g0v/twly_crawler" target="_blank">資料抓取程式</a></dd></p>
                    <p><dd><a href="https://github.com/thewayiam/twly_fileHandler" target="_blank">資料處理程式</a></dd></p>
                    <p><dd><a href="https://github.com/g0v/twly-voter-guide" target="_blank">網站程式</a></dd></p>
                    <dt>APIs</dt>
                    <p><dd><a href="/api/" target="_blank">APIs</a></dd></p>
                    <dt>意見回饋</dt>
                    <p><dd><a href="https://g0v.hackpad.com/--dMc3UYvwTjT" target="_blank">登入後直接打字</a>，歡迎各種意見回饋，一同為台灣人提供更好的工具平台努力。<br>公開討論信箱：g0v-ly@googlegroups.com</dd></p>
                </dl>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $(document).ready( function() {
            $('#about').addClass('active');
            $(".collapse").collapse()
        });
    </script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block title %}
        {% endblock title %}
        <meta name="keywords" content="立委投票指南,台灣,立委,立法委員,委員會,法案,立法院,表決,投票,選舉,候選人,公民" />
        <meta name="description" content="減少盲目投票，讓民主社會的台灣更進步" />
        <meta property="fb:admins" content="TaiwanLy"/>
        <meta property="fb:app_id" content="562924493762519"/>
        <meta property="og:type" content="website"/>
        <meta property="og:site_name" content="立委投票指南"/>
        <meta property="og:url" content="http://vote.ly.g0v.tw{{ request.path }}"/>
        <meta property="og:description" content="減少盲目投票，讓民主社會的台灣更進步"/>
        <meta property="og:image" content="https://s3.amazonaws.com/vote.ly.g0v.tw/facebook-og-image.png"/>
        <meta itemprop="description" content="減少盲目投票，讓民主社會的台灣更進步">
        <meta itemprop="image" content="https://s3.amazonaws.com/vote.ly.g0v.tw/facebook-og-image.png">
        <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
        <link href="{% static "css/bootstrap-responsive.min.css" %}" rel="stylesheet">
        <link href="{% static "css/g0v.css" %}" rel="stylesheet">
        <link rel="shortcut icon" href="https://s3-ap-southeast-1.amazonaws.com/councilor.tw/favicon.ico.png">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
        <link href="{% static "css/style.css" %}" rel="stylesheet">
        <link href="{% static "css/style-responsive.css" %}" rel="stylesheet">
        <link href="{% static "css/navbar-custom.css" %}" rel="stylesheet">
        <!--[if lt IE 9]>
        <script src="//cdnjs.bootcss.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
        <![endif]-->
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
            ga('create', 'UA-41993330-1', 'auto');
            ga('send', 'pageview');
        </script>
    </head>
    <body id="top">
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1";
            fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <i class="fa fa-angle-down"></i>
                    </a>
                    <a class="brand" href="/"><i class="fa fa-compass">立委投票指南</i></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li id="candidates" class="visible-desktop"><a href="{% url 'candidates:counties' ad=9 %}" >2016候選人</a></li>
                            <li id="ly" class="dropdown visible-desktop">
                                <a data-target="#" class="dropdown-toggle" data-toggle="dropdown">找立委 <i class="fa fa-angle-down"></i></a>
                                <ul class="dropdown-menu">
                                    <li class="dropdown-submenu">
                                        <a data-toggle="dropdown" data-target="#" >北部</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'legislator:county' '臺北市' %}" >臺北市</a></li>
                                            <li><a href="{% url 'legislator:county' '新北市' %}" >新北市</a></li>
                                            <li><a href="{% url 'legislator:county' '桃園市' %}" >桃園市</a></li>
                                            <li><a href="{% url 'legislator:county' '基隆市' %}" >基隆市</a></li>
                                            <li><a href="{% url 'legislator:county' '宜蘭縣' %}" >宜蘭縣</a></li>
                                            <li><a href="{% url 'legislator:county' '新竹市' %}" >新竹市</a></li>
                                            <li><a href="{% url 'legislator:county' '新竹縣' %}" >新竹縣</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a data-toggle="dropdown" data-target="#" >中部</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'legislator:county' '苗栗縣' %}" >苗栗縣</a></li>
                                            <li><a href="{% url 'legislator:county' '臺中市' %}" >臺中市</a></li>
                                            <li><a href="{% url 'legislator:county' '彰化縣' %}" >彰化縣</a></li>
                                            <li><a href="{% url 'legislator:county' '雲林縣' %}" >雲林縣</a></li>
                                            <li><a href="{% url 'legislator:county' '南投縣' %}" >南投縣</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a data-toggle="dropdown" data-target="#" >南部</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'legislator:county' '嘉義縣' %}" >嘉義縣</a></li>
                                            <li><a href="{% url 'legislator:county' '嘉義市' %}" >嘉義市</a></li>
                                            <li><a href="{% url 'legislator:county' '臺南市' %}" >臺南市</a></li>
                                            <li><a href="{% url 'legislator:county' '高雄市' %}" >高雄市</a></li>
                                            <li><a href="{% url 'legislator:county' '屏東縣' %}" >屏東縣</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a data-toggle="dropdown" data-target="#" >東部</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'legislator:county' '花蓮縣' %}" >花蓮縣</a></li>
                                            <li><a href="{% url 'legislator:county' '臺東縣' %}" >臺東縣</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown-submenu">
                                        <a data-toggle="dropdown" data-target="#" >離島</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'legislator:county' '澎湖縣' %}" >澎湖縣</a></li>
                                            <li><a href="{% url 'legislator:county' '金門縣' %}" >金門縣</a></li>
                                            <li><a href="{% url 'legislator:county' '連江縣' %}" >連江縣</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="{% url 'legislator:county' '山地原住民' %}" >山地原住民</a></li>
                                    <li><a href="{% url 'legislator:county' '平地原住民' %}" >平地原住民</a></li>
                                    <li><a href="{% url 'legislator:county' '全國不分區' %}" >全國不分區</a></li>
                                    <li><a href="{% url 'legislator:county' '僑居國外國民' %}" >僑居國外國民</a></li>
                                    <li><a href="{% url 'legislator:counties' %}" >全部</a></li>
                                </ul>
                            </li>
                            <li id="nav_bills" class="visible-desktop"><a href="{% url 'bill:bills' %}">找法案</a></li>
                            <li id="vote" class="visible-desktop"><a href="{% url 'vote:votes' %}" >找表決</a></li>
                            <li id="chart_report" class="dropdown visible-desktop">
                            <a data-target="#" class="dropdown-toggle" data-toggle="dropdown">相關圖表 <i class="fa fa-angle-down"></i></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'legislator:chart_report' 'conscience_vote' %}" >脫黨表決次數<small>前十名</small></a></li>
                                <li><a href="{% url 'legislator:chart_report' 'vote' %}" >立法院表決缺席<small>前十名</small></a></li>
                                <li><a href="{% url 'legislator:chart_report' 'ly' %}" >立法院開會缺席<small>前十名</small></a></li>
                                <li><a href="{% url 'legislator:chart_report' 'biller' %}" >法條修正草案數<small>前十名</small></a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'legislator:index' 'not_voting' %}" >投票缺席率(多&rarr;少)</a></li>
                                <li><a href="{% url 'legislator:index' 'conflict' %}" >脫黨投票率(多&rarr;少)</a></li>
                            </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row-fluid">
                {% block right %}
                {% endblock right %}
            </div>
        </div>

        <footer class="footer">
            <div align="center" class="container">
                <span class="fb-like" style="display: inline" data-href="https://www.facebook.com/TW.Voter.Guide/" data-layout="button_count" data-action="like" data-size="large" data-show-faces="true" data-share="true"></span>
                <a id="about" href="{% url 'about' %}">關於本站</a>
                <a id="reference" href="{% url 'reference' %}">資料來源</a>
                <a id="power_by" href="https://grants.g0v.tw/power" target="_blank"><img src="https://grants.g0v.tw/images/power/poweredby-square-i.png" style="height: 28px"></a>
            </div>
        </footer>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
        <script src="{% static "js/bootstrap.min.js" %}" type="text/javascript"></script>
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'twly'; // required: replace example with your forum shortname
            var disqus_url = '{{current_url}}';
            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <script type="text/javascript">
            $(document).ready( function() {
                $('#ly.dropdown, #chart_report.dropdown').hover(function(){
                    $('.dropdown-toggle', this).trigger('click');
                });
            });
        </script>
        {% block script %}
        {% endblock script %}
    </body>
</html>

templates/home.html
{% extends "base.html" %}
{% load highlight %}

{% block title %}
    <title>立委投票指南</title>
    <meta property="og:title" content="立委投票指南"/>
    <meta itemprop="name" content="立委投票指南">
{% endblock %}

{% block right %}
    <div class="page-header hidden-phone" align="center">
        <h4><i class="fa fa-compass"> <b>減少盲目投票，讓民主社會的台灣更進步。</b></i></h2>
        <p>請選擇縣市，或你所關心的議題、候選人</p>
    </div>
    <div class="span12">
        <div class="span2">
        </div>
        <div class="span4">
            <div>
                <h4><i class="fa fa-group fa-lg"></i> 找候選人</h4>
                {% include "common/search_name_form.html" with placeholder_text="請輸入候選人或縣市名稱" %}
            </div>
            <div class="btn-group">
                <a class="btn btn-moonc hidden-desktop" href="{% url 'candidates:counties' ad=9 %}">找縣市 <i class="fa fa-angle-down"></i></a>
                <a class="btn btn-moonc dropdown-toggle hidden-phone hidden-tablet" href="#" data-toggle="dropdown">找縣市 <i class="fa fa-angle-down"></i></a>
                <ul class="dropdown-menu">
                    <li class="dropdown-submenu">
                        <a data-toggle="dropdown" data-target="#" >北部</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'candidates:districts' county='臺北市' ad=9 %}">臺北市</a></li>
                            <li><a href="{% url 'candidates:districts' county='新北市' ad=9 %}">新北市</a></li>
                            <li><a href="{% url 'candidates:districts' county='桃園市' ad=9 %}">桃園市</a></li>
                            <li><a href="{% url 'candidates:districts' county='基隆市' ad=9 %}">基隆市</a></li>
                            <li><a href="{% url 'candidates:districts' county='宜蘭縣' ad=9 %}">宜蘭縣</a></li>
                            <li><a href="{% url 'candidates:districts' county='新竹縣' ad=9 %}">新竹縣</a></li>
                            <li><a href="{% url 'candidates:districts' county='新竹市' ad=9 %}">新竹市</a></li>
                        </ul>
                    </li>
                    <li class="dropdown-submenu">
                        <a data-toggle="dropdown" data-target="#" >中部</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'candidates:districts' county='苗栗縣' ad=9 %}">苗栗縣</a></li>
                            <li><a href="{% url 'candidates:districts' county='臺中市' ad=9 %}">臺中市</a></li>
                            <li><a href="{% url 'candidates:districts' county='彰化縣' ad=9 %}">彰化縣</a></li>
                            <li><a href="{% url 'candidates:districts' county='雲林縣' ad=9 %}">雲林縣</a></li>
                            <li><a href="{% url 'candidates:districts' county='南投縣' ad=9 %}">南投縣</a></li>
                        </ul>
                    </li>
                    <li class="dropdown-submenu">
                        <a data-toggle="dropdown" data-target="#" >南部</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'candidates:districts' county='嘉義縣' ad=9 %}">嘉義縣</a></li>
                            <li><a href="{% url 'candidates:districts' county='嘉義市' ad=9 %}">嘉義市</a></li>
                            <li><a href="{% url 'candidates:districts' county='臺南市' ad=9 %}">臺南市</a></li>
                            <li><a href="{% url 'candidates:districts' county='高雄市' ad=9 %}">高雄市</a></li>
                            <li><a href="{% url 'candidates:districts' county='屏東縣' ad=9 %}">屏東縣</a></li>
                        </ul>
                    </li>
                    <li class="dropdown-submenu">
                        <a data-toggle="dropdown" data-target="#" >東部</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'candidates:districts' county='花蓮縣' ad=9 %}">花蓮縣</a></li>
                            <li><a href="{% url 'candidates:districts' county='臺東縣' ad=9 %}">臺東縣</a></li>
                        </ul>
                    </li>
                    <li class="dropdown-submenu">
                        <a data-toggle="dropdown" data-target="#" >離島</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'candidates:districts' county='澎湖縣' ad=9 %}">澎湖縣</a></li>
                            <li><a href="{% url 'candidates:districts' county='金門縣' ad=9 %}">金門縣</a></li>
                            <li><a href="{% url 'candidates:districts' county='連江縣' ad=9 %}">連江縣</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'candidates:districts' county='山地原住民' ad=9 %}">山地原住民</a></li>
                    <li><a href="{% url 'candidates:districts' county='平地原住民' ad=9 %}">平地原住民</a></li>
                    <li><a href="{% url 'candidates:districts' county='全國不分區' ad=9 %}">全國不分區</a></li>
                    <li><a href="{% url 'candidates:districts' county='僑居國外國民' ad=9 %}">僑居國外國民</a></li>
                    <li><a href="{% url 'candidates:counties' ad=9 %}" >全部</a></li>
                </ul>
            </div>
        </div>
        <hr class="visible-phone">
        <div class="span4">
            <div>
                <h4><i class="fa fa-file-text fa-lg"></i> 找議題</h4>
                {% include "common/search_keyword_form.html" with placeholder_text="請輸入關心的議題" %}
            </div>
            <p>
            {% if hot_keyword %}
                <i class="fa fa-search"> 熱門搜尋：</i>
                    {% for keyword in hot_keyword %}
                        <a href="{% url 'home' %}?keyword={{keyword}}" rel="tooltip" title="包含此關鍵字的表決、法案"><b style="color: #9F0050;">{{keyword}}&nbsp;&nbsp;</b></a>
                    {% endfor %}
            {% endif %}
            {% if hot_standpoints %}
                <br><i class="fa fa-tag"> 熱門網友標籤：</i>
                    {% for standpoint in hot_standpoints %}
                        <a href="{% url 'vote:votes' %}?tag={{standpoint.title}}" rel="tooltip" title="包含此標籤的表決"><b style="color: #9F0050;">{{standpoint.title}}&nbsp;&nbsp;</b></a>
                    {% endfor %}
            {% endif %}
            </p>
        </div>
        <div class="span2">
        </div>
    </div>
    <br>
    {% if keyword %}
    <div class="span12">
        <div class="span1">
        </div>
        <div class="span5 hero-unit">
            <div class="well well-small">
                <font class="lead">
                    {{ votes|length }} 個有關<font style="color: red;">"{{keyword}}"</font>的表決
                </font>
            </div>
            {% if votes %}
                <ul class="media-list">
                    {% for fragment in votes %}
                        {% include "vote/vote_summary.html" %}
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="span5 hero-unit">
            <div class="well well-small">
                <font class="lead">
                    {{ bills|length }} 個有關<font style="color: red;">"{{keyword}}"</font>的法案
                </font>
            </div>
            {% if bills %}
                <ul class="media-list">
                    {% for fragment in bills %}
                        {% include "bill/bill_summary.html" %}
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="span1">
        </div>
    {% endif %}
    <div class="span12">
        <div id="disqus_thread"></div>
    </div>
{% endblock right %}

{% block script %}
    {% include "common/keyword_auto_complete.html" %}
    <script type="text/javascript">
        $(document).ready( function() {
            $("[rel='tooltip']").tooltip();
        });
    </script>
{% endblock script %}